export function getColors(isDark: boolean) {
  const brown = '#7B3A10';
  const brownDark = '#4E2600';
  const brownLight = '#fdf6f0';

  return isDark ? {
    bg: '#121212',
    card: '#1e1e1e',
    border: '#2c2c2c',
    borderLight: '#252525',
    green: brown,
    greenDark: brownDark,
    greenLight: '#1a1614',
    accent: brown,
    accentText: '#D2691E',
    accentBorder: brown,
    accentBtn: brown,
    btnGreen: brown,
    btnDark: '#2c2c2c',
    btnBlue: '#3f51b5',
    btnOrange: '#f4511e',
    btnTeal: '#4db6ac',
    text: '#f2f2f2',
    textSub: '#aaaaaa',
    textMuted: '#666666',
    white: '#ffffff',
    danger: '#ff453a',
    headerBg: '#000000',
    headerText: '#ffffff',
    tabBg: '#1e1e1e',
    inputBg: '#2a2a2a',
    sectionHeader: '#1a1a1a',
    unitRowActive: '#1a1614',
  } : {
    bg: '#f8f8f8',
    card: '#ffffff',
    border: '#e8e8e8',
    borderLight: '#f0f0f0',
    green: brown,
    greenDark: brownDark,
    greenLight: brownLight,
    accent: brown,
    accentText: brown,
    accentBorder: brown,
    accentBtn: brown,
    btnGreen: brown,
    btnDark: '#37474f',
    btnBlue: '#3f51b5',
    btnOrange: '#f4511e',
    btnTeal: '#4db6ac',
    text: '#1c1c1e',
    textSub: '#48484a',
    textMuted: '#8e8e93',
    white: '#ffffff',
    danger: '#ff3b30',
    headerBg: brown,
    headerText: '#ffffff',
    tabBg: '#ffffff',
    inputBg: '#fdfdfd',
    copyright: '#8e8e93',
    sectionHeader: '#f5f5f5',
    unitRowActive: brownLight,
  };
}

